### PR TITLE
Signup Functionality Added

### PR DESCRIPTION
**Pull request by 091karan**
User can signup using username and password.

### CODE REVIEW

**Comment by 091karan** [comment]
Social Authentication is added.

**Comment by AkshJain99** [comment]
have you tried these changes on local host???

**Comment by 091karan** [comment]
Yeah I did. They were working fine.

**Comment by AkshJain99** [comment]
nice work keep it up!!!

**Comment by 091karan** [comment]
Thanks. :)

**Comment by AkshJain99** [comment]
@091karan please resend those two PRs for password reset signup functionality and github and google authentication as something essy happened and the content of your pr is removed from code
moreover your contributiion will be marked from 5th dec so you have to again send those pr so that they can be counted as evaluation

**Comment by 091karan** [comment]
Hello @AkshJain99 . I checked the code, and content of my PR are already there. So when I try to make new PR then it is showing me "no changes detected"
Actually I am quite new to GitHub and am really unsure of how to resend the PRs.
Can you please guide me?

**Pull request merged**
