### PR TITLE
Fix README.md

### PR DESCRIPTION
**Pull request by akashgiricse**

### CODE REVIEW

**Review by AkshJain99 — CHANGES_REQUESTED** [review]
this is not something what you need to do ,this issue is about making more efforts in making readme.md rather editing previous content

**Comment by akashgiricse** [comment]
Ok. Got it. Thanks :+1:

**Comment by akashgiricse** [comment]
@AkshJain99, Can I add instructions to getting started with development in README? For example, how to run the project on your local machine. An instruction such as cloning, running the development server, migrations etc?

**Comment by AkshJain99** [comment]
yes you can do that ,that is something what is actually needed??

**Comment by akashgiricse** [comment]
It can help newcomers to set up their project easily on their local machine. 
Also, I'm planning to add an RSS feed to the posts. Is that a relevant feature? Can I work on it?

**Comment by AkshJain99** [comment]
yes your idea is sounding good okay you can work on it and add another issue for that and work on it and if it seems to be good i will merge it :+1:

**Comment by akashgiricse** [comment]
Ok. Thanks.

**Review by AkshJain99 — APPROVED** [review]

**Pull request merged**
